In [2]:
import numpy as np
test_array=[1,2,3,4,5]
tarray=np.array(test_array,float)
print(tarray.ndim)

1


In [3]:
print(tarray.size)

5


In [4]:
tarray.itemsize

8

In [5]:
x=np.array([[1,2,3,4],[1,2,3,4]],int)
x.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [13]:
import numpy as np
x=np.array(range(1,11)).reshape(2,5)
x[0,3]

4

In [14]:
x[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [16]:
x=np.array(range(1,11),int).reshape(2,5)
x[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [21]:
range(-5,5)

range(-5, 5)

In [27]:
np.zeros(shape=(2,5),dtype=np.int8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [35]:
np.empty(shape=(2,4),dtype=np.float32)

array([[0.000000e+00, 1.401298e-45, 0.000000e+00, 7.806146e-39],
       [1.631111e-42, 0.000000e+00, 1.076197e-42, 4.722376e-43]],
      dtype=float32)

In [44]:
x=np.arange(12).reshape(3,4)
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:
np.empty_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
matrix=np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [49]:
np.random.uniform(0,5,10)

array([2.27222386, 4.21954389, 3.37906606, 3.96730731, 4.22243668,
       1.09234097, 4.38664091, 3.34071345, 4.26009332, 2.57370202])

In [50]:
np.random.normal(0,2,10)

array([ 1.62070954,  1.53361696, -2.30840907,  2.22371734, -1.6271759 ,
        1.46163586,  0.05005287, -0.74567031,  2.7914146 , -4.04005428])

In [52]:
test_array = np.arange(1,13).reshape(3,4)
third_array=np.array([test_array,test_array,test_array])
third_array.shape

(3, 3, 4)

In [55]:
third_array.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [56]:
test_array = np.arange(1,13).reshape(3,4)
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [57]:
x_1=np.array([[1,2]])
x_2=np.array([[1,2]]).T
x_1.dot(x_2)

array([[5]])

In [2]:
import numpy as np
x=np.array([4,3,2,6,8,5])
y=np.array([2,1,7,8,9,3])
x>y

array([ True,  True, False, False, False,  True])

In [9]:
cond=x>3
x[cond]
x.take(cond)

array([3, 4, 4, 3, 3, 3])

In [10]:
cond.shape
cond

array([ True, False, False,  True,  True,  True])

In [6]:
x

array([4, 3, 2, 6, 8, 5])

In [7]:
x=np.array([4,3,2,6,8,5])
cond=np.array([1,2,0,0,3,3,3],int)
x[cond]

array([3, 2, 4, 4, 6, 6, 6])

In [8]:
x.take(cond)

array([3, 2, 4, 4, 6, 6, 6])

In [4]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

list_data= [1,2,3,4,5]
list_name=["a","b","c","d","e"]
example_obj = Series(data = list_data, index=list_name)
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [7]:
example_obj.name="number"
example_obj.index.name="id"
example_obj

id
a    1
b    2
c    3
d    4
e    5
Name: number, dtype: int64

In [8]:
dict_data = {"a":1, "b":2, "c":3, "d":4, "e":5}
indexes = ["a","b","c","d","e","f","g","h"]
series_obj = Series(dict_data, index=indexes)
series_obj

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64

In [4]:
 'https://archive.ics.uci.edu/ml/machinelearning-databases/housing/housing.data' 

'https://archive.ics.uci.edu/ml/machine\x02learning-databases/housing/housing.data'

In [6]:
import pandas as pd
from pandas import Series,DataFrame

raw_data={'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],'age': [42, 52, 36, 24, 73],'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}
df= pd.DataFrame(raw_data,columns=['first_name','last_name','age','city'])
df

first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [7]:

DataFrame(raw_data,columns=['first_name','last_name','age','city','debt'])


first_name last_name  age           city debt
0      Jason    Miller   42  San Francisco  NaN
1      Molly  Jacobson   52      Baltimore  NaN
2       Tina       Ali   36          Miami  NaN
3       Jake    Milner   24        Douglas  NaN
4        Amy     Cooze   73         Boston  NaN

In [8]:
df.head(5)

first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [9]:
df.tail(3)

first_name last_name  age     city
2       Tina       Ali   36    Miami
3       Jake    Milner   24  Douglas
4        Amy     Cooze   73   Boston

In [10]:
df.index=df["age"]
del df["age"]
df.head()

first_name last_name           city
age                                    
42       Jason    Miller  San Francisco
52       Molly  Jacobson      Baltimore
36        Tina       Ali          Miami
24        Jake    Milner        Douglas
73         Amy     Cooze         Boston

In [14]:
new_df=df.reset_index()

In [15]:
new_df

age first_name last_name           city
0   42      Jason    Miller  San Francisco
1   52      Molly  Jacobson      Baltimore
2   36       Tina       Ali          Miami
3   24       Jake    Milner        Douglas
4   73        Amy     Cooze         Boston

In [16]:
df.loc[42:]

first_name last_name           city
age                                    
42       Jason    Miller  San Francisco
52       Molly  Jacobson      Baltimore
36        Tina       Ali          Miami
24        Jake    Milner        Douglas
73         Amy     Cooze         Boston

In [22]:
df.loc[:],["first_name","last_name"]

SyntaxError: invalid syntax (2000512176.py, line 1)

In [23]:
new_df

age first_name last_name           city
0   42      Jason    Miller  San Francisco
1   52      Molly  Jacobson      Baltimore
2   36       Tina       Ali          Miami
3   24       Jake    Milner        Douglas
4   73        Amy     Cooze         Boston

In [24]:
new_df.iloc[:2,:4]

age first_name last_name           city
0   42      Jason    Miller  San Francisco
1   52      Molly  Jacobson      Baltimore

In [32]:
new_df.drop(2)

age first_name last_name           city
0   42      Jason    Miller  San Francisco
3   24       Jake    Milner        Douglas
4   73        Amy     Cooze         Boston

In [35]:
new_df

age first_name last_name           city
0   42      Jason    Miller  San Francisco
3   24       Jake    Milner        Douglas
4   73        Amy     Cooze         Boston

In [38]:
new_df.drop("age",axis=1)

first_name last_name           city
0      Jason    Miller  San Francisco
3       Jake    Milner        Douglas
4        Amy     Cooze         Boston

In [10]:
import pandas as pd
import numpy as np
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings','kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],'Year': [2014, 2015, 2014, 2015, 2014, 2015, 2016, 2017, 2016, 2014, 2015, 2017],
'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df=pd.DataFrame(ipl_data)
df

Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [14]:
MultiGroupby=df.groupby(["Team","Rank"])["Points"].sum()

In [15]:
MultiGroupby.index

MultiIndex([('Devils', 2),
            ('Devils', 3),
            ( 'Kings', 1),
            ( 'Kings', 3),
            ('Riders', 1),
            ('Riders', 2),
            ('Royals', 1),
            ('Royals', 4),
            ( 'kings', 4)],
           names=['Team', 'Rank'])

In [16]:
MultiGroupby["Devils":"Kings"]

Team    Rank
Devils  2        863
        3        673
Kings   1       1544
        3        741
Name: Points, dtype: int64

In [17]:
MultiGroupby.unstack()

Rank         1       2      3      4
Team                                
Devils     NaN   863.0  673.0    NaN
Kings   1544.0     NaN  741.0    NaN
Riders   876.0  2173.0    NaN    NaN
Royals   804.0     NaN    NaN  701.0
kings      NaN     NaN    NaN  812.0

In [18]:
MultiGroupby.swaplevel()

Rank  Team  
2     Devils     863
3     Devils     673
1     Kings     1544
3     Kings      741
1     Riders     876
2     Riders    2173
1     Royals     804
4     Royals     701
      kings      812
Name: Points, dtype: int64

In [20]:
grouped = df.groupby("Year")
grouped.get_group(2014)

Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701

In [21]:
grouped.agg(min)

Team  Rank  Points
Year                      
2014  Devils     1     701
2015  Devils     1     673
2016   Kings     1     694
2017   Kings     1     690

In [23]:
import numpy as np
grouped.agg(np.mean)

C:\Users\user\AppData\Local\Temp\ipykernel_2612\2658144929.py:2: FutureWarning: The operation <function mean at 0x000002A0D72C8AF0> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  grouped.agg(np.mean)


Rank  Points
Year              
2014   2.5  795.25
2015   2.5  769.50
2016   1.5  725.00
2017   1.5  739.00

In [28]:
df.groupby('Year')

In [29]:
df.groupby('Team').filter(
lambda x: 
x["Points"].max() > 800)

Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
5    kings     4  2015     812
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [34]:
import pandas as pd # pandas 모듈 호출
raw_data = { 'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],'test_score': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
df_left = pd.DataFrame(raw_data, columns = ['subject_id', 'test_score'])
df_left

subject_id  test_score
0          1          51
1          2          15
2          3          15
3          4          61
4          5          16
5          7          14
6          8          15
7          9           1
8         10          61
9         11          16

In [36]:
raw_data = {'subject_id': ['4', '5', '6', '7', '8'],'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty' ],
'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan' ]}
df_right = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_right

subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [37]:
pd.merge(left=df_left, right=df_right, how="inner", 
on='subject_id')

subject_id  test_score first_name last_name
0          4          61      Billy    Bonder
1          5          16      Brian     Black
2          7          14      Bryce     Brice
3          8          15      Betty    Btisan

In [38]:
pd.merge(left=df_left, right=df_right, how="outer")

subject_id  test_score first_name last_name
0           1        51.0        NaN       NaN
1           2        15.0        NaN       NaN
2           3        15.0        NaN       NaN
3           4        61.0      Billy    Bonder
4           5        16.0      Brian     Black
5           7        14.0      Bryce     Brice
6           8        15.0      Betty    Btisan
7           9         1.0        NaN       NaN
8          10        61.0        NaN       NaN
9          11        16.0        NaN       NaN
10          6         NaN       Bran   Balwner

In [3]:
import pandas as pd
raw_Data={'first_name':['Jason','Molly','Tina','Jake','Amy'],
         'last_name':['Miller','Jacobson','Ali','Milner','cooze'],
         'age':[42,52,36,24,73]}
df=pd.DataFrame(raw_Data,index=['a','b','c','d','e'])


In [11]:
df["a"]

KeyError: 'a'

In [13]:
nested_dict={'Korea':{2019:4.6,202:5.7,2021:4.8},'Japan':{2020:1.5,2020:1.5,2021:1.6}}
df=pd.DataFrame(nested_dict)
df

Korea  Japan
2019    4.6    NaN
202     5.7    NaN
2021    4.8    1.6
2020    NaN    1.5

In [14]:
df=pd.DataFrame(nested_dict).T
df

2019  202   2021  2020
Korea   4.6   5.7   4.8   NaN
Japan   NaN   NaN   1.6   1.5

In [34]:
data=[['Choi',29],['Kim',32],['Jung',27],['Lee',25]]
df=pd.DataFrame(data,columns=['Name','Age'],index=[1,2,3,4])
df.iloc[2]["Age"]

27

In [40]:
df

Name  Age
1  Choi   29
2   Kim   32
3  Jung   27
4   Lee   25

In [41]:
df_new=df[["New"]]

KeyError: "None of [Index(['New'], dtype='object')] are in the [columns]"

In [6]:
import pandas as pd
import numpy as np
df1=pd.DataFrame(np.arange(16).reshape(4,4))
df2=pd.DataFrame([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
df1.dot(df2)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [45]:
df1=pd.DataFrame(np.arange(25).reshape(5,5),columns=list("abcde"))
df2=pd.DataFrame(np.arange(16).reshape(4,4),columns=list("abcd"))
(df1+df2).fillna(0)

a     b     c     d    e
0   0.0   2.0   4.0   6.0  0.0
1   9.0  11.0  13.0  15.0  0.0
2  18.0  20.0  22.0  24.0  0.0
3  27.0  29.0  31.0  33.0  0.0
4   0.0   0.0   0.0   0.0  0.0

In [46]:
df=pd.DataFrame(np.arange(1,17).reshape(4,4))
df

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [48]:
(df+df.mean(axis=1))**2

0       1       2       3
0   12.25   72.25  182.25  342.25
1   56.25  156.25  306.25  506.25
2  132.25  272.25  462.25  702.25
3  240.25  420.25  650.25  930.25

In [4]:
import pandas as pd
data=[["choi",29],["kim",32],["jung",27],["lee",25]]
df=pd.DataFrame(data,columns=['Name','Age'],index=[1,2,3,4])
df

Name  Age
1  choi   29
2   kim   32
3  jung   27
4   lee   25

In [5]:
df=df.drop("Age")

KeyError: "['Age'] not found in axis"

In [ ]:
df