In [4]:
import numpy as np
x=np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [5]:
x.ndim

3

In [7]:
x.reshape(-1,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
x=np.array(range(12)).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
x[:,1:2]

array([[1],
       [5],
       [9]])