In [1]:
import numpy as np
Y_true=np.array([1,1,0,1,1])
Y_pred=np.array([0.23,0.5,0.99,0.69,0.4])
np.sqrt(np.sum(Y_true-Y_pred)**2/len(Y_true))

0.5321841786449499

In [2]:
diff=(Y_true-Y_pred)
np.sqrt(diff**2/len(Y_true))

array([0.34435447, 0.2236068 , 0.44274146, 0.13863621, 0.26832816])

In [4]:
np.sqrt(np.sum(np.square((Y_true-Y_pred)))/len(Y_true))

0.6751444289927897

In [5]:
diff=(Y_true-Y_pred)
np.sqrt(diff.T.dot(diff)/len(Y_true))

0.6751444289927896

In [13]:
A=np.array([8,1,2,2,3,4,5,6,7,8])
Z=(A-np.mean(A))/np.std(A)

In [14]:
Z

array([ 1.38344038, -1.46481923, -1.057925  , -1.057925  , -0.65103077,
       -0.24413654,  0.16275769,  0.56965192,  0.97654615,  1.38344038])

In [16]:
test_a=np.arange(1,10).reshape(3,3)
test_b=np.arange(6).reshape(2,3)
test_a.dot(test_b.T)

array([[ 8, 26],
       [17, 62],
       [26, 98]])

In [17]:
arr=np.arange(16).reshape(4,4)
print(arr.size-(arr.shape[0]*arr.ndim))

8


In [18]:
arr=np.arange(20).reshape(10,2)
x,y=arr.shape
print(arr.reshape(y,x).shape)

(2, 10)


In [20]:
arr=np.arange(8)
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr.reshape(2,-2)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
arr.reshape(arr.size)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
arr_1=np.arange(4)
arr_2=np.arange(4,0,-1)
np.all(arr_1<arr_2)

False

In [26]:
a=np.arange(6).reshape(2,3)
b=a>4
a[b]

array([5])

In [27]:
b

array([[False, False, False],
       [False, False,  True]])

In [28]:
a.take(b)

array([[0, 0, 0],
       [0, 0, 1]])

In [29]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
Z=np.array([6,6,6,4,7,9,1,8,8,4])
Z[Z.argsort()[:5]]=0
print(Z)

[0 0 6 0 7 9 0 8 8 0]


In [35]:
arr=np.array([[17,27,14,11],[8,24,25,26],[11,26,26,23],[3,30,4,25],[22,18,24,11]])
arr[[0,2,1]]

array([[17, 27, 14, 11],
       [11, 26, 26, 23],
       [ 8, 24, 25, 26]])