In [5]:
import numpy as np
matrix=np.array(range(9)).reshape(3,3)
matrix


array([0, 4, 8])

In [6]:
np.random.uniform(0,5,10)

array([4.16053132, 0.06710569, 2.77962901, 3.92956459, 3.24073832,
       1.72903786, 3.25359322, 0.95362246, 3.44357991, 2.73268768])

In [8]:
np.random.normal(0,2,10)

array([-0.15388114, -2.73621661,  0.59928723,  0.00838411, -0.29092336,
        2.5760083 , -1.28340566,  2.17819504, -0.30900204,  0.57205551])

In [9]:
x=np.array([4,6,7,3,2])
x>5

array([False,  True,  True, False, False])

In [10]:
np.where(x>5)

(array([1, 2], dtype=int64),)

In [11]:
np.where(x>5,10,20)

array([20, 10, 10, 20, 20])

In [22]:
x=np.array([4,6,7,3,2])
np.argsort(x)

array([4, 3, 0, 1, 2], dtype=int64)

In [23]:
x>3

array([ True,  True,  True, False, False])

In [24]:
x[x>3]

array([4, 6, 7])

In [25]:
cond=x>3
x[cond]

array([4, 6, 7])

In [26]:
x.shape

(5,)

In [27]:
cond.shape

(5,)

In [33]:
import pandas as pd
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url,sep='\s+')
df=pd.DataFrame(df_data)
df

0.00632  18.00  2.310  0  0.5380  6.5750  65.20  4.0900  1  296.0  15.30  \
0    0.02731    0.0   7.07  0   0.469   6.421   78.9  4.9671  2  242.0   17.8   
1    0.02729    0.0   7.07  0   0.469   7.185   61.1  4.9671  2  242.0   17.8   
2    0.03237    0.0   2.18  0   0.458   6.998   45.8  6.0622  3  222.0   18.7   
3    0.06905    0.0   2.18  0   0.458   7.147   54.2  6.0622  3  222.0   18.7   
4    0.02985    0.0   2.18  0   0.458   6.430   58.7  6.0622  3  222.0   18.7   
..       ...    ...    ... ..     ...     ...    ...     ... ..    ...    ...   
500  0.06263    0.0  11.93  0   0.573   6.593   69.1  2.4786  1  273.0   21.0   
501  0.04527    0.0  11.93  0   0.573   6.120   76.7  2.2875  1  273.0   21.0   
502  0.06076    0.0  11.93  0   0.573   6.976   91.0  2.1675  1  273.0   21.0   
503  0.10959    0.0  11.93  0   0.573   6.794   89.3  2.3889  1  273.0   21.0   
504  0.04741    0.0  11.93  0   0.573   6.030   80.8  2.5050  1  273.0   21.0   

     396.90  4.98  24.00  
0    396.90  9.14   21.6  
1    392.83  4.03   34.7  
2    394.63  2.94   33.4  
3    396.90  5.33   36.2  
4    394.12  5.21   28.7  
..      ...   ...    ...  
500  391.99  9.67   22.4  
501  396.90  9.08   20.6  
502  396.90  5.64   23.9  
503  393.45  6.48   22.0  
504  396.90  7.88   11.9  

[505 rows x 14 columns]